---
title: Teacher Hero
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hi@teacherhero.me
description: 'Teacher Hero is an open source tool to manage classrooms, grades and
  students.

'
baseurl: ''
url: https://teacherhero.me
github_username: teacherhero
markdown: kramdown
