# Site settings
title: Teacher Hero
email: hi@teacherhero.me
description: > # this means to ignore newlines until "baseurl:"
  Teacher Hero is an open source tool to manage classrooms, grades and students.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://teacherhero.me"
github_username:  teacherhero

# Build settings
markdown: kramdown
